---
- name: Test connectivity to all hosts
  hosts: all
  remote_user: ubuntu
  gather_facts: yes

  tasks:

    - name: Ensure /home/ubuntu/mydir exists
      ansible.builtin.file:
        path: /home/ubuntu/mydir    # <-- change this path to whatever directory you want
        state: directory
        mode: '0755'                # permissions
        owner: ubuntu
        group: ubuntu
        
    - name: Raw echo test
      ansible.builtin.raw: echo "OK"
