name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Terraform Init
      - name: Terraform Init
        run: terraform init 

      # Terraform Format Check
      - name: Terraform Format
        run: terraform fmt 

      # Terraform Validate.
      - name: Terraform Validate
        run: terraform validate

      # Terraform Apply (optional for PRs)
      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: Get Terraform Output
        run: terraform output -json > tf_output.json

      - name: Output tf.json
        run: cat tf_output.json

      - name: Generate Ansible inventory using jq
        run: |
          echo "[frontend]" > inventory.ini
          terraform output -json backend_instance_ids | jq -r '.value[]' >> inventory.ini
          echo "" >> inventory.ini
          echo "[backend]" >> inventory.ini
          terraform output -json backend_private_ips | jq -r '.value[]' >> inventory.ini

      - name: Show inventory file
        run: cat inventory.ini
