name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Terraform Init
      - name: Terraform Init
        run: terraform init 

      # Terraform Format Check
      - name: Terraform Format
        run: terraform fmt 

      # Terraform Validate.
      - name: Terraform Validate
        run: terraform validate

      # Terraform Apply (optional for PRs)
      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: Get Terraform Output
        run: terraform output -json > tf_output.json

      - name: Output tf.json
        run: cat tf_output.json

      - name: Install Ansible and AWS dependencies
        run: |
          sudo apt update -y
          sudo apt install python3-pip -y
          pip3 install ansible boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: test aws ec2 plugin
        run: ansible-doc -t inventory amazon.aws.aws_ec2

      - name: Output inventory graph
        run: ansible-inventory -i aws_ec2.yml --graph

      - name: Output inventory graph
        run: cat aws_ec2.yml 
      
